[project]
name = "deltacycle"
version = "0.39.0"
description = "Delta Cycle"
readme = "README.md"

requires-python = ">=3.12"
dependencies = []

[project.urls]
Repository = "https://github.com/cjdrake/deltacycle.git"

[dependency-groups]
dev = [
    "ipykernel>=6.29.5",
    "pyrefly>=1.1.1",
    "pyright>=1.1.411",
    "pytest>=8.3.5",
    "pytest-cov>=6.1.1",
    "pytest-profiling>=1.8.1",
    "ruff>=0.11.9",
    "ty>=0.0.33",
]
doc = [
    "sphinx>=9.1.0",
    "sphinx-autobuild>=2025.8.25",
    "sphinx-book-theme>=1.4.0",
]

[tool.pyrefly]
search-path = ["src", "."]

[tool.pyright]
typeCheckingMode = "strict"
