line-length = 100

[lint]

# https://docs.astral.sh/ruff/rules
select = [
    "E4",   # pycodestyle
    "E7",
    "E9",
    "F",    # pyflakes
    "PL",   # pylint
]

ignore = [
    "PLR2004",  # magic-value-comparison
    "PLW0120",  # useless-else-on-loop
    "PLW0603",  # global-statement
]
